name: Generate Monthly Bible Calendar

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 on the 1st of every month
  workflow_dispatch:     # Allow manual run from GitHub web UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run script to generate ICS
      run: python generate_bible_calendar.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add *.ics
        git commit -m "📅 Auto-update calendar file for new month" || echo "No changes"
        git push
